"""
Sub-agent: turn a Jira ticket into a small GitLab file change (Groq or deterministic fallback).
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

from agent_network.config import groq_base_url, groq_model, is_llm_enabled, llm_provider

logger = logging.getLogger(__name__)

_ARTIFACT_SCHEMA = """
Return ONLY valid JSON (no markdown fences) with keys:
- file_path: relative path under repo root (prefer docs/agent-network-tasks/{ticket_id}.md)
- file_content: markdown body for the new file
- summary: one-line MR summary (max 120 chars)
"""


def _fallback_artifact(ticket_id: str, title: str, description: str) -> dict[str, str]:
    body = (description or "").strip() or "_No description provided on the ticket._"
    return {
        "file_path": f"docs/agent-network-tasks/{ticket_id}.md",
        "file_content": (
            f"# {title.strip()}\n\n"
            f"**Ticket:** {ticket_id}\n\n"
            f"## Description\n\n{body}\n\n"
            f"## Implementation notes\n\n"
            f"_Auto-generated by Agent Network sub-agent (deterministic fallback)._\n"
        ),
        "summary": title.strip()[:120] or f"Implement {ticket_id}",
    }


def _parse_artifact_json(text: str, ticket_id: str, title: str, description: str) -> dict[str, str]:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        obj = json.loads(cleaned)
    except json.JSONDecodeError:
        return _fallback_artifact(ticket_id, title, description)
    if not isinstance(obj, dict):
        return _fallback_artifact(ticket_id, title, description)

    file_path = str(obj.get("file_path", "")).strip()
    file_content = str(obj.get("file_content", "")).strip()
    summary = str(obj.get("summary", "")).strip()
    if not file_path or not file_content:
        return _fallback_artifact(ticket_id, title, description)
    if ".." in file_path or file_path.startswith("/"):
        return _fallback_artifact(ticket_id, title, description)
    if not summary:
        summary = title.strip()[:120] or f"Implement {ticket_id}"
    return {
        "file_path": file_path,
        "file_content": file_content,
        "summary": summary[:120],
    }


def generate_task_artifact(ticket_id: str, title: str, description: str) -> dict[str, str]:
    """
    Sub-agent entry: produce {file_path, file_content, summary} for GitLab commit.
    Uses Groq when configured; otherwise deterministic markdown file.
    """
    if not is_llm_enabled() or llm_provider() != "groq":
        return _fallback_artifact(ticket_id, title, description)

    try:
        from openai import OpenAI
        import os

        client = OpenAI(
            base_url=groq_base_url(),
            api_key=os.environ["GROQ_API_KEY"],
            timeout=60.0,
        )
        prompt = (
            f"You are a software sub-agent. A Jira ticket needs a minimal, reviewable "
            f"documentation artifact committed to GitLab.\n\n"
            f"Ticket ID: {ticket_id}\n"
            f"Title: {title}\n"
            f"Description:\n{description or '(empty)'}\n\n"
            f"{_ARTIFACT_SCHEMA}"
        )
        response = client.chat.completions.create(
            model=groq_model(),
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
        )
        content = (response.choices[0].message.content or "").strip()
        if not content:
            return _fallback_artifact(ticket_id, title, description)
        return _parse_artifact_json(content, ticket_id, title, description)
    except Exception as e:
        logger.warning("Groq sub-agent failed, using fallback: %s", e)
        return _fallback_artifact(ticket_id, title, description)
